export const CONTENT_TEST_ID = "CONTENT_TEST_ID";
export const REQUEST_INVITE_BUTTON_TEST_ID = "REQUEST_INVITE_BUTTON_TEST_ID";
export const REQUEST_INVITE_FORM_TEST_ID = "REQUEST_INVITE_FORM_TEST_ID";
